"""
API Endpoints for Backlink Toxicity Analysis.
Identifies spam/toxic referring domains.
"""
from typing import List, Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

from app.models.database import BacklinkProfile, Project

router = APIRouter()


# ============== REQUEST/RESPONSE MODELS ==============
class BacklinkCheckRequest(BaseModel):
    project_id: str
    referring_domain: str
    referring_page: str
    target_page: str
    anchor_text: str


class BacklinkResponse(BaseModel):
    id: str
    referring_domain: str
    referring_page: str
    target_page: str
    anchor_text: str
    toxic_score: float
    is_suspicious: bool
    suspicion_reasons: List[str]
    disavow_recommended: bool
    disavowed: bool
    discovered_at: str


# ============== ENDPOINTS ==============
@router.post("/analyze")
async def analyze_backlink(request: BacklinkCheckRequest):
    """
    Analyze a backlink for toxicity and spam indicators.
    """
    project = await Project.get(request.project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    # Calculate toxicity score
    toxic_score, reasons = _calculate_toxicity(
        request.referring_domain,
        request.anchor_text
    )
    
    backlink = BacklinkProfile(
        project_id=request.project_id,
        referring_domain=request.referring_domain,
        referring_page=request.referring_page,
        target_page=request.target_page,
        anchor_text=request.anchor_text,
        metrics={
            "toxic_score": toxic_score,
            "domain_authority": None,
            "trust_flow": None,
            "citation_flow": None,
            "first_seen": datetime.utcnow(),
            "last_checked": datetime.utcnow()
        },
        is_suspicious=len(reasons) > 0,
        suspicion_reasons=reasons,
        disavow_recommended=toxic_score > 0.7
    )
    
    await backlink.insert()
    
    return _backlink_to_response(backlink)


@router.get("/profile/{project_id}", response_model=List[BacklinkResponse])
async def get_backlink_profile(
    project_id: str,
    toxic_only: bool = False,
    limit: int = Query(default=100, le=500)
):
    """
    Get all backlinks for a project.
    
    Optionally filter to show only toxic/suspicious links.
    """
    query = BacklinkProfile.find(BacklinkProfile.project_id == project_id)
    
    if toxic_only:
        query = query.find(BacklinkProfile.toxic_score > 0.5)
    
    backlinks = await query.sort(-BacklinkProfile.metrics.toxic_score).limit(limit).to_list()
    
    return [_backlink_to_response(b) for b in backlinks]


@router.get("/disavow-list/{project_id}")
async def generate_disavow_list(project_id: str):
    """
    Generate a disavow.txt formatted list of toxic domains.
    """
    toxic_links = await BacklinkProfile.find(
        BacklinkProfile.project_id == project_id,
        BacklinkProfile.disavow_recommended == True,
        BacklinkProfile.disavowed == False
    ).to_list()
    
    # Extract unique domains
    domains = set()
    for link in toxic_links:
        domains.add(link.referring_domain)
    
    disavow_text = "# Generated by SEO Command Center\n"
    disavow_text += f"# Total domains: {len(domains)}\n\n"
    disavow_text += "\n".join(f"domain:{d}" for d in sorted(domains))
    
    return {
        "total_domains": len(domains),
        "disavow_format": disavow_text,
        "domains": sorted(domains)
    }


@router.post("/mark-disavowed/{backlink_id}")
async def mark_disavowed(backlink_id: str):
    """
    Mark a backlink as disavowed.
    """
    backlink = await BacklinkProfile.get(backlink_id)
    if not backlink:
        raise HTTPException(status_code=404, detail="Backlink not found")
    
    backlink.disavowed = True
    await backlink.save()
    
    return {"message": "Backlink marked as disavowed"}


def _calculate_toxicity(domain: str, anchor: str) -> tuple:
    """
    Calculate toxicity score based on various spam indicators.
    """
    from datetime import datetime
    
    score = 0.0
    reasons = []
    
    # Check for spam TLDs
    spam_tlds = ['.xyz', '.tk', '.ml', '.cf', '.ga', '.top', '.click', '.link']
    if any(domain.endswith(tld) for tld in spam_tlds):
        score += 0.3
        reasons.append("Spam TLD detected")
    
    # Check for excessive exact match anchors
    if len(anchor) > 30 and anchor.count(' ') < 2:
        score += 0.2
        reasons.append("Potential exact-match anchor")
    
    # Check for suspicious patterns
    if any(x in domain for x in ['porn', 'xxx', 'casino', 'viagra', 'loan']):
        score += 0.5
        reasons.append("Suspicious content indicators")
    
    # Check for numeric-heavy domains
    digit_count = sum(c.isdigit() for c in domain)
    if digit_count > len(domain) * 0.3:
        score += 0.2
        reasons.append("Numeric-heavy domain")
    
    return min(score, 1.0), reasons


def _backlink_to_response(backlink: BacklinkProfile) -> BacklinkResponse:
    return BacklinkResponse(
        id=str(backlink.id),
        referring_domain=backlink.referring_domain,
        referring_page=backlink.referring_page,
        target_page=backlink.target_page,
        anchor_text=backlink.anchor_text,
        toxic_score=backlink.metrics.toxic_score,
        is_suspicious=backlink.is_suspicious,
        suspicion_reasons=backlink.suspicion_reasons,
        disavow_recommended=backlink.disavow_recommended,
        disavowed=backlink.disavowed,
        discovered_at=backlink.discovered_at.isoformat()
    )
